### ISSUE TITLE
the offline verifier does not work

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/data-accounting-external-verifier#18]
timotheus@system001 data-accounting-external-verifier (mcr_compatibility) $ ./verify.js --file ~/Downloads/Main_Page_Test.xml
Verifying Main Page
Page Verification Hashes:  [
  '8389ea1d134aee30359151c9f3d67ebf939f9edff307ca6572e54f132f5c49d5129c48719a13f38df92b21c1906502bc85c2b41cccc18bc5d445d769262d9e8f',
  '28dd742cae472d5546a99688b56a26ee021b398a0a43a87f828f2b81039faf41de6919df41ad5dca184338c73812271cbfd97b596460a3eb51e7e6a6a9754042',
  'f74c57ce5f446c8f85a2fa4b9231a428e65890c2ee74211d4ebe1aa6d32aed5edd906cdd0b9770d67ff1b4ee0509476233f81f5b0ccb3f02b3b4f19db621a5a9',
  'c8955a5aa760972b06dff1c76556896d540d4240a07707e2d674e1e79401dd6af475a90f5d4f70c9c6d4aedfc3703f767088fd9efde4eb6aa69e0276a805a742',
  'ef3eabf54e397af20a3656b27650c24e22d1178f509e5ab96436a869e9dfd79bef448402241d2f5638e3f32b0cbdc928c78755760a5589a031c6e1258c195ac6',
  'e17631da61adfcfe0cafc4c0b89946b30cb9f8da0f9a5fa72f402dac988b421b8c6fe369048bb131aba89e5d5106b293ea3ff1308f2815b6f6e1bf61214e99e9'
]
1. Verification of 8389ea1d134aee30359151c9f3d67ebf939f9edff307ca6572e54f132f5c49d5129c48719a13f38df92b21c1906502bc85c2b41cccc18bc5d445d769262d9e8f.
Content hash doesn't match
Status: INVALID

**Comment by rht** [comment]
No, it works. You're probably on mcr branch, which is expected that it doesn't work.
